# Generated by Django 3.2.4 on 2021-06-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='redirect_permanently',
            field=models.BooleanField(default=False, verbose_name='انتقال دائم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='redirect_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_from', to='market.market', verbose_name='انتقال به'),
        ),
        migrations.DeleteModel(
            name='Redirect',
        ),
    ]
