# Generated by Django 3.2.4 on 2021-06-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210618_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='redirect_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_from', to='market.market', verbose_name='انتقال به'),
        ),
    ]
