# Generated by Django 3.2.4 on 2021-06-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_market_redirect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='redirect_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_from', to='market.market', verbose_name='انتقال به'),
        ),
    ]
