# Generated by Django 3.2.4 on 2021-06-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0005_alter_market_redirect_permanently'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='redirect_permanently',
        ),
        migrations.RemoveField(
            model_name='market',
            name='redirect_to',
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveIntegerField()),
                ('to_object_id', models.PositiveIntegerField()),
                ('from_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'market'), ('model', 'Market')), models.Q(('app_label', 'market'), ('model', 'Product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='redirected_from', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'market'), ('model', 'Market')), models.Q(('app_label', 'market'), ('model', 'Product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='redirected_to', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('desc', models.CharField(max_length=500, verbose_name='جزئیات')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.market', verbose_name='حجره')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
