# Generated by Django 3.2.4 on 2021-06-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0007_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='redirect_permanently',
            field=models.BooleanField(default=False, null=True, verbose_name='انتقال دائم'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='from_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'market'), ('model', 'market')), models.Q(('app_label', 'market'), ('model', 'product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='redirected_from', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='to_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'market'), ('model', 'market')), models.Q(('app_label', 'market'), ('model', 'product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='redirected_to', to='contenttypes.contenttype'),
        ),
    ]
