# Generated by Django 3.2.4 on 2021-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210619_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='to_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='redirect',
            old_name='from_object_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='from_content_type',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='to_object_id',
        ),
        migrations.AddField(
            model_name='redirect',
            name='redirect_url',
            field=models.URLField(default='https://www.google.com', max_length=100, verbose_name='آدرس جدید'),
            preserve_default=False,
        ),
    ]
