# Generated by Django 3.2.4 on 2021-06-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0009_auto_20210619_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='content_type',
            new_name='dst_content_type',
        ),
        migrations.RenameField(
            model_name='redirect',
            old_name='object_id',
            new_name='dst_object_id',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='redirect_url',
        ),
        migrations.AddField(
            model_name='redirect',
            name='src_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'market'), ('model', 'market')), models.Q(('app_label', 'market'), ('model', 'product')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_from', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='src_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
