# Generated by Django 3.2.4 on 2021-06-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0010_auto_20210619_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='dst_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'market'), ('model', 'market')), models.Q(('app_label', 'market'), ('model', 'product')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_to', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='dst_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
