# Generated by Django 3.2.4 on 2021-06-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20210619_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('deactive', 'غیرفعال')], default='active', max_length=8, verbose_name='وضعیت'),
        ),
    ]
