# Generated by Django 3.2.4 on 2021-06-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_product_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('market', 'name')},
        ),
    ]
