# Generated by Django 3.2.4 on 2021-06-13 06:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره همراه')),
                ('verification_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='کد تایید')),
                ('code_expire_datetime', models.DateTimeField(blank=True, null=True, verbose_name='انقضا کد تایید')),
            ],
            managers=[
                ('phone', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('phone', django.db.models.manager.Manager()),
            ],
        ),
    ]
