# Generated by Django 3.2.4 on 2021-06-13 13:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210613_0651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreRegister',
            new_name='VerificationCode',
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='verificationcode',
            managers=[
                ('verificaiton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='code_expire_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
    ]
